'''
####################################################################################################
@author Auto-generated by the GunnsDraw supexport script version 19.5.0 on 2026-02-22 19:49:40.469554
####################################################################################################
'''

import trick

# Add the given sub-networks to the given super-network.  The super-network is not finalized, and
# link port connections are not changed.
def MixingNetworkSuperAddNetworks(superNet,    # the super-network
                                  MixingNetwork,             # sub-network type MixingNetwork
                                  MixingNetworkInterface,    # sub-network type MixingNetworkInterface
                                  ):
    superNet.addSubNetwork(MixingNetwork)
    superNet.addSubNetwork(MixingNetworkInterface)

# Finalize the super-network with its nodes and solver configuration data.
def MixingNetworkSuperFinalize(superNet):
    superNet.registerSuperNodes()
    superNet.netSolverConfig.mConvergenceTolerance      =  1.0000
    superNet.netSolverConfig.mMinLinearizationPotential =  0.001
    superNet.netSolverConfig.mMinorStepLimit            =  10
    superNet.netSolverConfig.mDecompositionLimit        =  1
    superNet.netSolver.setIslandMode(trick.Gunns.SOLVE)

# Change the link port assignments to connect them between sub-networks.
# NOTE: sub-networks must be added to the super-network before this is called.
def MixingNetworkSuperMoveLinks(MixingNetwork,             # sub-network type MixingNetwork
                                MixingNetworkInterface,    # sub-network type MixingNetworkInterface
                                ):
    # Get super-node number offset for each sub-network.
    superNetwork = MixingNetwork.getSuperNetwork()
    super_ground = superNetwork.netNodeList.mNumNodes - 1
    offset_MixingNetwork          = MixingNetwork.getNodeOffset()
    offset_MixingNetworkInterface = MixingNetworkInterface.getNodeOffset()

    # Override initial link node mapping.
    #
    # Link MixingNetwork.pipe_1
    map_MixingNetwork_pipe_1 = trick.alloc_type(2, "int")
    map_MixingNetwork_pipe_1 = [0+offset_MixingNetworkInterface, 0+offset_MixingNetwork]
    MixingNetwork.netInput.pipe_1.mInitialNodeMap = map_MixingNetwork_pipe_1


# This is the all-in-one call to configure and finalize this super-network and updated the link
# connections.  This should only be used if this super-network is not going to be added to a
# higher-level super-network.
def MixingNetworkSuperSetup(superNet,    # the super-network
                            MixingNetwork,             # sub-network type MixingNetwork
                            MixingNetworkInterface,    # sub-network type MixingNetworkInterface
                            ):
    # Add the sub-networks.
    MixingNetworkSuperAddNetworks(superNet,    # the super-network
                                  MixingNetwork,             # sub-network type MixingNetwork
                                  MixingNetworkInterface,    # sub-network type MixingNetworkInterface
                                  )

    # Configure the super-network.
    MixingNetworkSuperFinalize(superNet)

    # Change link connections.
    MixingNetworkSuperMoveLinks(MixingNetwork,             # sub-network type MixingNetwork
                                MixingNetworkInterface,    # sub-network type MixingNetworkInterface
                                )

